/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CourtAndGoAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CourtAndGoAdminSite": {
      "type": "sst.aws.React"
      "url": string
    }
    "CourtAndGoDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}